[build]
  command   = "next build"
  publish   = ".next"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

